<?php
/**
 *
 */
?>

.dropbox-list {
	width: 100%;
	margin-left: auto;
	margin-right: auto;
}
.dropbox-list thead th {
	font-weight: bold;
	text-align: center;
	border-bottom: 1px solid #000;
	border-style: dotted;
}
.dropbox-list .selector {
	text-align: left;
	width: 25px;
}
.dropbox-list .filename {
	text-align: left;
}
.dropbox_buttons {
	-webkit-border-radius: 8px;
	-moz-border-radius: 8px;
	background:white;
	margin:5px 10px;
	padding:5px;
}
.dropbox_buttons input {
	margin:0 0 0 10px;
}
.dropbox_buttons input[type="button"] {
	font: 12px/100% Arial, Helvetica, sans-serif;
	font-weight: bold;
	color: #4690D6;
	background:#dddddd;
	border: 1px solid #999999;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	width: auto;
	height: 25px;
	padding: 2px 6px 2px 6px;
	margin:0 0 0 10px;
	cursor: pointer;
}
.dropbox_buttons input[type="button"]:hover {
	background: #0054a7;
	border: 1px solid #0054a7;
	color:white;
}

.sprite{padding-bottom: 0px; padding-left: 16px;width:16px;height:16px;background-image:url("<?php echo $vars['url']; ?>mod/dropbox/graphics/sprites.png");background-repeat:no-repeat}
.s_page_paste{background-position:left -3460px;}
.s_email_go{background-position:left -1736px;}
.s_comment_add{background-position:left -1095px;}
.s_computer_add{background-position:left -1180px;}
.s_basket_remove{background-position:left -535px;}
.s_time_go{background-position:left -5331px;}
.s_big-dropdown-gray{background-position:left -569px;}
.s_folder_page{background-position:left -2181px;}
.s_page_white_sound_blue{background-position:left -4310px;}
.s_page_white_c{background-position:left -3596px;}
.s_folder_gray{background-position:left -2164px;}
.s_facebook{background-position:left -1891px;}
.s_link_delete_blue{background-position:left -3018px;}
.s_arrow_switch{background-position:left -442px;}
.s_email_delete{background-position:left -1702px;}
.s_application_double{background-position:left -170px;}
.s_picture_save_gray{background-position:left -4667px;}
.s_page_white_csharp{background-position:left -3749px;}
.s_gift_blue{background-position:left -2542px;}
.s_page_white_php_blue{background-position:left -4157px;}
.s_clock{background-position:left -976px;}
.s_drive_magnify{background-position:left -1532px;}
.s_hide_del{background-position:left -2758px;}
.s_time_back{background-position:left -5246px;}
.s_page_white_actionscript_blue{background-position:left -3545px;}
.s_medal_gold_3{background-position:left -3171px;}
.s_new{background-position:left -3239px;}
.s_green_close{background-position:left -2605px;}
.s_control_pause_blue{background-position:left -1282px;}
.s_email_blue{background-position:left -1685px;}
.s_user_go_blue{background-position:left -5603px;}
.s_page_white_code_blue{background-position:left -3647px;}
.s_page_white_vector{background-position:left -4429px;}
.s_redx{background-position:left -4816px;width:15px;height:15px}
.s_page_white_gear{background-position:left -3970px;}
.s_wand{background-position:left -5705px;}
.s_coins{background-position:left -1044px;}
.s_camera{background-position:left -824px;}
.s_time_delete{background-position:left -5297px;}
.s_iphone{background-position:left -2860px;width:14px;height:21px}
.s_world_link_blue{background-position:left -5909px;}
.s_folder_blue{background-position:left -2045px;}
.s_pencil{background-position:left -4531px;}
.s_picture_save{background-position:left -4650px;}
.s_delete_blue{background-position:left -1367px;}
.s_link_delete{background-position:left -3001px;}
.s_phone{background-position:left -4548px;}
.s_user_suit_blue{background-position:left -5654px;}
.s_application_edit{background-position:left -221px;}
.s_folder_photos_blue{background-position:left -2232px;}
.s_link_break{background-position:left -2967px;}
.s_star_blue_on{background-position:left -5058px;width:11px;height:11px}
.s_weather_clouds_blue{background-position:left -5756px;}
.s_package_go{background-position:left -3392px;}
.s_purge{background-position:left -4782px;}
.s_sort-uptick-off{background-position:left -4933px;width:11px;height:10px}
.s_comment_add_blue{background-position:left -1112px;}
.s_emoticon_smile{background-position:left -1787px;}
.s_twitter_blue{background-position:left -5416px;}
.s_heart{background-position:left -2707px;}
.s_folder_user_delete{background-position:left -2402px;}
.s_page_white_stack{background-position:left -4327px;}
.s_big-dropdown{background-position:left -586px;}
.s_lock{background-position:left -3052px;}
.s_bullet_toggle_plus{background-position:left -756px;}
.s_calendar_view_month{background-position:left -807px;}
.s_table_multiple{background-position:left -5152px;}
.s_chart_bar_blue{background-position:left -909px;}
.s_page_white_paint{background-position:left -4106px;}
.s_white_pause{background-position:left -5790px;}
.s_hide_del_blue{background-position:left -2775px;}
.s_comment_blue{background-position:left -1129px;}
.s_house_go_blue{background-position:left -2809px;}
.s_folder_edit{background-position:left -2096px;}
.s_events_bubble_tail{background-position:left -1868px;width:4px;height:5px}
.s_page_white_put{background-position:left -4242px;}
.s_page_white_paint_blue{background-position:left -4123px;}
.s_information{background-position:left -2826px;}
.s_aol{background-position:left -85px;}
.s_mac{background-position:left -3103px;}
.s_page_white_compressed{background-position:left -3664px;}
.s_link_break_blue{background-position:left -2984px;}
.s_cog_blue{background-position:left -1027px;}
.s_world_link{background-position:left -5892px;}
.s_page_white_visualstudio{background-position:left -4446px;}
.s_wrench{background-position:left -5926px;}
.s_page_white_powerpoint_blue{background-position:left -4225px;}
.s_sort-downtick-off{background-position:left -4911px;width:11px;height:10px}
.s_application_add{background-position:left -102px;}
.s_checkbox{background-position:left -942px;}
.s_help{background-position:left -2724px;}
.s_time_go_blue{background-position:left -5348px;}
.s_bullet_toggle_minus{background-position:left -739px;}
.s_page_white_delete_blue{background-position:left -3800px;}
.s_page_white_delete{background-position:left -3783px;}
.s_group{background-position:left -2622px;}
.s_money_blue{background-position:left -3222px;}
.s_checkbox_checked{background-position:left -959px;}
.s_camera_blue{background-position:left -841px;}
.s_bullet_minus{background-position:left -705px;}
.s_thick_x{background-position:left -5203px;width:8px;height:8px}
.s_application_go{background-position:left -255px;}
.s_package_edit{background-position:left -3375px;}
.s_mac_black{background-position:left -3120px;}
.s_creditcards{background-position:left -1316px;}
.s_user_add_blue{background-position:left -5467px;}
.s_page_white_word{background-position:left -4480px;}
.s_user_suit_minus{background-position:left -5671px;}
.s_application_delete_blue{background-position:left -153px;}
.s_lock_blue{background-position:left -3069px;}
.s_page_white_put_blue{background-position:left -4259px;}
.s_package_delete_blue{background-position:left -3358px;}
.s_book_open{background-position:left -671px;}
.s_page_white_picture_blue{background-position:left -4191px;}
.s_exclamation{background-position:left -1874px;}
.s_white_play{background-position:left -5807px;}
.s_star_blue_on_big{background-position:left -5070px;width:14px;height:13px}
.s_application_down{background-position:left -204px;}
.s_page_white_actionscript{background-position:left -3528px;}
.s_weather_clouds{background-position:left -5739px;}
.s_user_add{background-position:left -5450px;}
.s_user_suit_minus_blue{background-position:left -5688px;}
.s_group_add_blue{background-position:left -2656px;}
.s_emoticon_unhappy{background-position:left -1804px;}
.s_feed{background-position:left -1908px;}
.s_gray_logo{background-position:left -2576px;width:20px;height:20px}
.s_page_white_dvd{background-position:left -3817px;}
.s_email_delete_blue{background-position:left -1719px;}
.s_delete_gray{background-position:left -1384px;}
.s_page_white_sound{background-position:left -4293px;}
.s_coins_add{background-position:left -1061px;}
.s_page_white_visualstudio_blue{background-position:left -4463px;}
.s_page_white_compressed_blue{background-position:left -3681px;}
.s_page_white_stack_blue{background-position:left -4344px;}
.s_accept{background-position:left -0px;}
.s_star_blue{background-position:left -4989px;}
.s_page_white_edit_blue{background-position:left -3868px;}
.s_sync{background-position:left -5101px;}
.s_filter_down_blue{background-position:left -1959px;}
.s_digg{background-position:left -1401px;}
.s_page_white_text_width{background-position:left -4395px;}
.s_house_go{background-position:left -2792px;}
.s_page_white_excel{background-position:left -3885px;}
.s_page_white_flash{background-position:left -3936px;}
.s_application_delete{background-position:left -136px;}
.s_flame{background-position:left -1976px;width:17px;height:17px}
.s_email_open_blue{background-position:left -1770px;}
.s_minus{background-position:left -3188px;}
.s_add_gray{background-position:left -51px;}
.s_computer_go{background-position:left -1248px;}
.s_user_comment{background-position:left -5484px;}
.s_user_edit{background-position:left -5552px;}
.s_star_blue_half_big{background-position:left -5018px;width:14px;height:13px}
.s_folder_page_blue{background-position:left -2198px;}
.s_folder_public{background-position:left -2266px;}
.s_page_white_cup{background-position:left -3766px;}
.s_application_pencil{background-position:left -306px;}
.s_dropbox_arrow_down{background-position:left -1566px;}
.s_transmit{background-position:left -5365px;}
.s_page_white_picture{background-position:left -4174px;}
.s_world_grey{background-position:left -5875px;}
.s_folder_user_blue{background-position:left -2385px;}
.s_play{background-position:left -4735px;width:7px;height:12px}
.s_page_white_get{background-position:left -4004px;}
.s_folder_user_gray{background-position:left -2436px;}
.s_email_add_blue{background-position:left -1668px;}
.s_windows{background-position:left -5824px;}
.s_page_white{background-position:left -3477px;}
.s_link_blue{background-position:left -2950px;}
.s_picture_blue{background-position:left -4633px;}
.s_bomb{background-position:left -637px;}
.s_weather_clouds_white{background-position:left -5773px;}
.s_android_small{background-position:left -68px;}
.s_application_double_blue{background-position:left -187px;}
.s_star_grey{background-position:left -5084px;}
.s_layout{background-position:left -2916px;}
.s_folder_star{background-position:left -2300px;}
.s_photo{background-position:left -4565px;}
.s_folder{background-position:left -1994px;}
.s_page_white_magnify{background-position:left -4072px;}
.s_drive_delete{background-position:left -1515px;}
.s_half_star{background-position:left -2690px;width:9px;height:16px}
.s_application_link{background-position:left -289px;}
.s_sort-uptick-on{background-position:left -4944px;width:11px;height:10px}
.s_folder_go{background-position:left -2130px;}
.s_arrowleft{background-position:left -493px;width:12px;height:12px}
.s_page_white_go{background-position:left -4038px;}
.s_application_go_blue{background-position:left -272px;}
.s_x{background-position:left -5960px;width:8px;height:8px}
.s_page_white_gear_blue{background-position:left -3987px;}
.s_page_white_word_blue{background-position:left -4497px;}
.s_bullet_plus{background-position:left -722px;}
.s_computer{background-position:left -1163px;}
.s_dropdown_arrow_small2{background-position:left -1617px;}
.s_close{background-position:left -993px;}
.s_gmail{background-position:left -2559px;}
.s_world_blue{background-position:left -5858px;}
.s_pictures{background-position:left -4684px;}
.s_page_white_flash_blue{background-position:left -3953px;}
.s_arrow_turn_left{background-position:left -459px;}
.s_user_suit{background-position:left -5637px;}
.s_page_white_excel_blue{background-position:left -3902px;}
.s_arrow_refresh_blue{background-position:left -408px;}
.s_email{background-position:left -1634px;}
.s_folder_user_add_blue{background-position:left -2368px;}
.s_dropdown_arrow_small{background-position:left -1600px;}
.s_page_white_powerpoint{background-position:left -4208px;}
.s_table_edit{background-position:left -5135px;}
.s_folder_photos{background-position:left -2215px;}
.s_page_white_tux{background-position:left -4412px;}
.s_pictures_blue{background-position:left -4701px;}
.s_key{background-position:left -2899px;}
.s_arrow_refresh_small{background-position:left -425px;}
.s_star_blue_off_big{background-position:left -5044px;width:14px;height:13px}
.s_plugin{background-position:left -4748px;}
.s_text_align_justify{background-position:left -5186px;}
.s_page_white_copy{background-position:left -3698px;}
.s_cog{background-position:left -1010px;}
.s_page_white_get_blue{background-position:left -4021px;}
.s_comment{background-position:left -1078px;}
.s_application_add_blue{background-position:left -119px;}
.s_page_white_text_blue{background-position:left -4378px;}
.s_linux{background-position:left -3035px;}
.s_cancel{background-position:left -858px;}
.s_table{background-position:left -5118px;}
.s_package_blue{background-position:left -3324px;}
.s_page_white_text{background-position:left -4361px;}
.s_folder_add{background-position:left -2011px;}
.s_wrench_blue{background-position:left -5943px;}
.s_asterisk_blue{background-position:left -519px;width:16px;height:15px}
.s_folder_delete{background-position:left -2062px;}
.s_package_delete{background-position:left -3341px;}
.s_filter_down{background-position:left -1942px;}
.s_page_white_dvd_blue{background-position:left -3834px;}
.s_user_comment_blue{background-position:left -5501px;}
.s_share_arrow{background-position:left -4861px;width:15px;height:15px}
.s_folder_delete_blue{background-position:left -2079px;}
.s_events_bubble_right{background-position:left -1853px;width:2px;height:14px}
.s_group_blue{background-position:left -2673px;}
.s_x_8{background-position:left -5969px;}
.s_sound{background-position:left -4955px;}
.s_folder_star_blue{background-position:left -2317px;}
.s_download_arrow{background-position:left -1452px;}
.s_email_open{background-position:left -1753px;}
.s_page_white_add{background-position:left -3562px;}
.s_computer_edit{background-position:left -1231px;}
.s_help_blue{background-position:left -2741px;}
.s_folder_go_blue{background-position:left -2147px;}
.s_error{background-position:left -1821px;}
.s_newspaper{background-position:left -3256px;}
.s_arrow_out{background-position:left -357px;}
.s_page_white_magnify_blue{background-position:left -4089px;}
.s_page_white_go_blue{background-position:left -4055px;}
.s_telephone{background-position:left -5169px;}
.s_folder_user_share_20{background-position:left -2470px;width:20px;height:20px}
.s_folder_wrench{background-position:left -2491px;}
.s_sort-downtick-on{background-position:left -4922px;width:11px;height:10px}
.s_cross{background-position:left -1333px;}
.s_photo_blue{background-position:left -4582px;}
.s_dropbox_blue{background-position:left -1583px;}
.s_package_add{background-position:left -3290px;}
.s_application_edit_blue{background-position:left -238px;}
.s_x_green{background-position:left -5986px;width:8px;height:8px}
.s_magnifier_zoom_in{background-position:left -3154px;}
.s_user{background-position:left -5433px;}
.s_arrow_turn_up{background-position:left -476px;}
.s_star_blue_half{background-position:left -5006px;width:11px;height:11px}
.s_show_del{background-position:left -4877px;}
.s_folder_edit_blue{background-position:left -2113px;}
.s_cancel_blue{background-position:left -875px;}
.s_magnifier{background-position:left -3137px;}
.s_money{background-position:left -3205px;}
.s_page_white_cplusplus{background-position:left -3732px;}
.s_user_delete_blue{background-position:left -5535px;}
.s_world{background-position:left -5841px;}
.s_arrowright{background-position:left -506px;width:12px;height:12px}
.s_time_back_blue{background-position:left -5263px;}
.s_add{background-position:left -17px;}
.s_download_arrow_blue{background-position:left -1469px;}
.s_computer_delete{background-position:left -1214px;}
.s_pill{background-position:left -4718px;}
.s_add_blue{background-position:left -34px;}
.s_folder_public_blue{background-position:left -2283px;}
.s_ipad_small{background-position:left -2843px;}
.s_arrow_out_black{background-position:left -374px;}
.s_tick{background-position:left -5212px;}
.s_show_del_blue{background-position:left -4894px;}
.s_user_delete{background-position:left -5518px;}
.s_control_play_blue{background-position:left -1299px;}
.s_gift{background-position:left -2525px;}
.s_server{background-position:left -4844px;}
.s_blackberry{background-position:left -620px;}
.s_cake_blue{background-position:left -790px;}
.s_twitter{background-position:left -5399px;}
.s_packrat_leave{background-position:left -3443px;width:32px;height:16px}
.s_page_white_edit{background-position:left -3851px;}
.s_package_go_blue{background-position:left -3409px;}
.s_page_white_acrobat{background-position:left -3494px;}
.s_page_white_php{background-position:left -4140px;}
.s_page_white_c_blue{background-position:left -3613px;}
.s_arrow_blue{background-position:left -323px;}
.s_comments{background-position:left -1146px;}
.s_computer_go_blue{background-position:left -1265px;}
.s_user_go{background-position:left -5586px;}
.s_iphone_small{background-position:left -2882px;}
.s_door_in_blue{background-position:left -1435px;}
.s_time_delete_blue{background-position:left -5314px;}
.s_packrat{background-position:left -3426px;}
.s_login_arrow{background-position:left -3086px;}
.s_package{background-position:left -3273px;}
.s_big-dropdown_blue{background-position:left -603px;}
.s_plus{background-position:left -4765px;}
.s_arrow_highlight{background-position:left -340px;}
.s_page_white_blue{background-position:left -3579px;}
.s_wand_blue{background-position:left -5722px;}
.s_folder_add_blue{background-position:left -2028px;}
.s_star_blue_off{background-position:left -5032px;width:11px;height:11px}
.s_page_white_code{background-position:left -3630px;}
.s_gavel{background-position:left -2508px;}
.s_computer_add_blue{background-position:left -1197px;}
.s_page_white_copy_blue{background-position:left -3715px;}
.s_page_white_acrobat_blue{background-position:left -3511px;}
.s_time_blue{background-position:left -5280px;}
.s_folder_user_delete_blue{background-position:left -2419px;}
.s_page_white_ruby{background-position:left -4276px;}
.s_arrow_refresh{background-position:left -391px;}
.s_rounded_tl{background-position:left -4832px;width:5px;height:5px}
.s_basket_remove_blue{background-position:left -552px;}
.s_paypal{background-position:left -4514px;}
.s_link{background-position:left -2933px;}
.s_rounded_tr{background-position:left -4838px;width:5px;height:5px}
.s_bug{background-position:left -688px;}
.s_drive_add{background-position:left -1498px;}
.s_downtick-spacer{background-position:left -1486px;width:11px;height:11px}
.s_purge_blue{background-position:left -4799px;}
.s_cake{background-position:left -773px;}
.s_events_bubble_left{background-position:left -1838px;width:2px;height:14px}
.s_delete{background-position:left -1350px;}
.s_folder_user{background-position:left -2334px;}
.s_tshirt{background-position:left -5382px;}
.s_email_add{background-position:left -1651px;}
.s_check{background-position:left -926px;width:15px;height:15px}
.s_film{background-position:left -1925px;}
.s_package_add_blue{background-position:left -3307px;}
.s_folder_user_add{background-position:left -2351px;}
.s_book{background-position:left -654px;}
.s_door_in{background-position:left -1418px;}
.s_graynotch{background-position:left -2597px;width:3px;height:7px}
.s_picture{background-position:left -4616px;}
.s_star{background-position:left -4972px;}
.s_chart_bar{background-position:left -892px;}
.s_yahoo{background-position:left -5995px;}
.s_dropbox{background-position:left -1549px;}
.s_folder_plugin{background-position:left -2249px;}
.s_user_gray{background-position:left -5620px;}
.s_photos{background-position:left -4599px;}
.s_page_white_film{background-position:left -3919px;}
.s_time{background-position:left -5229px;}
.s_user_edit_blue{background-position:left -5569px;}
.s_folder_user_gray_blue{background-position:left -2453px;}
.s_group_add{background-position:left -2639px;}

a .sprite {
	margin-right: 5px;
}